/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 06fc945855ce8b28a2d2d2f8a5e5a33f)
interface __BaseEnv_Env {
	CONVERSATIONS_CACHE: KVNamespace;
	UPLOADS: R2Bucket;
	WIDGET_BUCKET: R2Bucket;
	DB: D1Database;
	CRAWL_QUEUE: Queue;
	AI: Ai;
	ASSETS: Fetcher;
	CF_ACCOUNT_ID: string;
	AI_MODEL: string;
	STRIPE_STARTER_MONTHLY_PRICE_ID: string;
	STRIPE_STARTER_ANNUAL_PRICE_ID: string;
	STRIPE_STANDARD_MONTHLY_PRICE_ID: string;
	STRIPE_STANDARD_ANNUAL_PRICE_ID: string;
	STRIPE_BUSINESS_MONTHLY_PRICE_ID: string;
	STRIPE_BUSINESS_ANNUAL_PRICE_ID: string;
	BETTER_AUTH_URL: string;
	BETTER_AUTH_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	RESEND_API_KEY: string;
	ENCRYPTION_KEY: string;
	GEMINI_API_KEY: string;
	OPENAI_API_KEY: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_PUBLISHABLE_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	RESEND_WEBHOOK_SECRET: string;
	INTERNAL_BROADCAST_SECRET: string;
	AUTORAG_API_TOKEN: string;
	CONVERSATION_DO: DurableObjectNamespace<import("./worker/index").ConversationDO>;
	MAVEN_PROJECT_AGENT: DurableObjectNamespace<import("./worker/index").MavenProjectAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
		durableNamespaces: "ConversationDO" | "MavenProjectAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CF_ACCOUNT_ID" | "AI_MODEL" | "STRIPE_STARTER_MONTHLY_PRICE_ID" | "STRIPE_STARTER_ANNUAL_PRICE_ID" | "STRIPE_STANDARD_MONTHLY_PRICE_ID" | "STRIPE_STANDARD_ANNUAL_PRICE_ID" | "STRIPE_BUSINESS_MONTHLY_PRICE_ID" | "STRIPE_BUSINESS_ANNUAL_PRICE_ID" | "BETTER_AUTH_URL" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "RESEND_API_KEY" | "ENCRYPTION_KEY" | "GEMINI_API_KEY" | "OPENAI_API_KEY" | "STRIPE_SECRET_KEY" | "STRIPE_PUBLISHABLE_KEY" | "STRIPE_WEBHOOK_SECRET" | "RESEND_WEBHOOK_SECRET" | "INTERNAL_BROADCAST_SECRET" | "AUTORAG_API_TOKEN">> {}
}
