// Generated by wrangler types -- manually simplified for compatibility

interface CrawlMessage {
  resourceId: string;
  projectId: string;
  url: string;
  depth: number;
  maxDepth: number;
  maxPages: number;
}

interface Env {
  DB: D1Database;
  UPLOADS: R2Bucket;
  WIDGET_BUCKET: R2Bucket;
  CONVERSATIONS_CACHE: KVNamespace;
  AI: Ai;
  ASSETS: Fetcher;
  CRAWL_QUEUE: Queue<CrawlMessage>;
  BETTER_AUTH_URL: string;
  BETTER_AUTH_SECRET: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_CLIENT_SECRET: string;
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  RESEND_API_KEY: string;
  ENCRYPTION_KEY: string;
  GEMINI_API_KEY: string;
  OPENAI_API_KEY: string;
  AI_MODEL: string;
  BROWSER_RENDERING_API_TOKEN: string;
  CF_ACCOUNT_ID: string;
  STRIPE_SECRET_KEY: string;
  STRIPE_WEBHOOK_SECRET: string;
  STRIPE_STARTER_MONTHLY_PRICE_ID: string;
  STRIPE_STARTER_ANNUAL_PRICE_ID: string;
  STRIPE_STANDARD_MONTHLY_PRICE_ID: string;
  STRIPE_STANDARD_ANNUAL_PRICE_ID: string;
  STRIPE_BUSINESS_MONTHLY_PRICE_ID: string;
  STRIPE_BUSINESS_ANNUAL_PRICE_ID: string;
}
