import type { ReactNode } from "react";
import type { DashboardNavDestinationId } from "@/lib/dashboard/nav";
import {
  AppearanceIcon,
  ArchivedIcon,
  ArticlesIcon,
  BehaviorIcon,
  BillingIcon,
  ChannelsIcon,
  ConnectedAppsIcon,
  ConnectorsIcon,
  CustomersIcon,
  GlobeIcon,
  GreetingsIcon,
  HelpHomeIcon,
  InboxIcon,
  InstallIcon,
  KnowledgeIcon,
  NeedsYouIcon,
  ProfileIcon,
  ProjectIcon,
  QuickActionsIcon,
  ResolvedIcon,
  SettingsIcon,
  SnoozedIcon,
  SpamIcon,
  TeamIcon,
  type NavIconProps,
} from "./nav-icons";

export const NAV_ICONS: Record<
  DashboardNavDestinationId,
  (props: NavIconProps) => ReactNode
> = {
  "needs-you": NeedsYouIcon,
  inbox: InboxIcon,
  snoozed: SnoozedIcon,
  resolved: ResolvedIcon,
  archived: ArchivedIcon,
  flagged: SpamIcon,
  customers: CustomersIcon,
  knowledge: KnowledgeIcon,
  behavior: BehaviorIcon,
  connectors: ConnectorsIcon,
  greetings: GreetingsIcon,
  "help-center": ArticlesIcon,
  "help-home": HelpHomeIcon,
  settings: SettingsIcon,
  "settings-appearance": AppearanceIcon,
  "settings-quick-actions": QuickActionsIcon,
  "settings-install": InstallIcon,
  "settings-channels": ChannelsIcon,
  "settings-help-center": GlobeIcon,
  "settings-connected-apps": ConnectedAppsIcon,
  "settings-project": ProjectIcon,
  "settings-team": TeamIcon,
  "settings-billing": BillingIcon,
  "settings-profile": ProfileIcon,
};
